# ---------------------------------------------------------------
# Unity
# ---------------------------------------------------------------
unity:  "{_config_source}/applications/unity.yaml"

# ---------------------------------------------------------------
# Houdini
# ---------------------------------------------------------------
houdini:  "{_config_source}/applications/houdini.yaml"

# ---------------------------------------------------------------
# Maya
# ---------------------------------------------------------------
maya:  "{_config_source}/applications/maya.yaml"

# ---------------------------------------------------------------
# Adobe
# ---------------------------------------------------------------
photoshop:  "{_config_source}/applications/photoshop.yaml"