location:
  linux:    ""
  windows:  "{drive}/Program Files/Adobe/Adobe Photoshop CC *"

product: "photoshop"

icon: "{_script_source}/source/icons/photoshop.png"

environment:
  windows: ""
  universal:
    - ""