- project_path: "{root}/{client}/{project}"
- context_path: "{project_path}/{context}"
- task_path: "{context_path}/{task}"
- department_path: "{task_path}/{department}"
- working_app: "{department_path}/{appname}"
- working_directory: "{department_path}/{appname}/{user}"